name: "🤖 Prep release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The new release version"
        type: "string"
        required: true

jobs:
  updates:
    name: "Prep release ${{ inputs.version }}"

    permissions:
      contents: "write"
      pull-requests: "write"

    strategy:
      matrix:
        include:
          - branch-name: "release/$VERSION"
            commit-title: "Update project metadata"
            pr-title: "Release v$VERSION"
            tox-label-create-changes: "prep-release"

    uses: "kurtmckee/github-workflows/.github/workflows/create-pr.yaml@dispatch-after-opening-pr"
    with:
      config: "${{ toJSON(matrix) }}"
      version: "${{ inputs.version }}"
