name: "✨ Updates"
on:
  workflow_dispatch: null

jobs:
  updates:
    name: "${{ 'Updates' || matrix.ignore }}"

    permissions:
      actions: "write"
      contents: "write"
      pull-requests: "write"

    strategy:
      matrix:
        include:
          - tox-label-create-changes: "update"
#            run-workflow: "test.yaml"

    uses: "kurtmckee/github-workflows/.github/workflows/create-pr.yaml@open-draft-prs"
    with:
      config: "${{ toJSON(matrix) }}"
